03/06/22 (23:19:17) | ERROR: The read operation timed out
Traceback (most recent call last):
  File "/home/allen/.miniconda/lib/python3.9/site-packages/bpytop.py", line 5029, in _checker
    with urllib.request.urlopen("https://github.com/aristocratos/bpytop/raw/master/bpytop.py", timeout=5) as source: # type: ignore
  File "/home/allen/.miniconda/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/allen/.miniconda/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/home/allen/.miniconda/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/home/allen/.miniconda/lib/python3.9/urllib/request.py", line 555, in error
    result = self._call_chain(*args)
  File "/home/allen/.miniconda/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/allen/.miniconda/lib/python3.9/urllib/request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/allen/.miniconda/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/home/allen/.miniconda/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/allen/.miniconda/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/allen/.miniconda/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/allen/.miniconda/lib/python3.9/urllib/request.py", line 1350, in do_open
    r = h.getresponse()
  File "/home/allen/.miniconda/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/home/allen/.miniconda/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/home/allen/.miniconda/lib/python3.9/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/allen/.miniconda/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/home/allen/.miniconda/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/allen/.miniconda/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
